<?php require 'includes/header.php'; $project=rows('projeto')[0]??[]; $estrategias=rows('estrategias','ordem'); $kpis=rows('kpis','id'); $team=rows('equipe'); $timeline=rows('timeline','ordem'); ?>
<section class="hero"><div><p class="eyebrow">EXPANSÃO · MARKETING · VENDAS · DADOS</p><h1>ScaleUp <em>LATAM & Europe</em></h1><h2>Estratégia de Marketing e Vendas Digitais para Expansão Internacional</h2><p class="lead">Uma plataforma de planejamento estratégico para conectar mercados, gerar demanda e orientar decisões com dados.</p><p><a class="button" href="#sobre">Conheça o Projeto</a> <a class="button ghost" href="#estrategia">Explorar Estratégia</a></p></div><div class="orb"><b>LATAM</b><i>↔</i><b>EUROPA</b><small>MARKETING · VENDAS · DATA · ROI</small></div></section>
<section id="sobre"><p class="eyebrow">VISÃO GERAL</p><h2>Sobre o projeto</h2><div class="grid info"><article><b>Projeto</b><strong><?=e($project['nome']??'ScaleUp LATAM & Europe')?></strong><span>ID 22782 · Desafio 163241</span></article><article><b>Período</b><strong>03/08/2026 — 19/09/2026</strong><span>Gerente: Mauro Claro · Mentor: Lucas</span></article><article><b>Capacidade</b><strong>26h semanais · 114h</strong><span>Equipe de três integrantes</span></article></div></section>
<section id="objetivo"><p class="eyebrow">DIREÇÃO</p><h2>Objetivo</h2><p class="wide"><?=e($project['objetivo']??'Desenvolver uma estratégia completa de marketing e vendas digitais para apoiar a expansão nos mercados da América Latina e Europa, integrando aquisição, conversão, rentabilidade, ROI e análise de dados.')?></p><div class="flow"><span>Lead</span><span>Qualificação</span><span>Conversão</span><span>Venda</span><span>Retenção</span><span>Análise</span></div></section>
<section id="justificativa"><p class="eyebrow">CONTEXTO</p><h2>Por que esta estratégia?</h2><div class="grid cards"><?php foreach(['Falta de estratégia clara de expansão','Baixa conversão de leads em vendas','Comunicação genérica e pouca adaptação cultural','Dificuldade em medir campanhas e ROI','Desalinhamento entre marketing e vendas'] as $x): ?><article><span class="icon">↗</span><h3><?=e($x)?></h3></article><?php endforeach ?></div></section>
<section id="estrategia"><p class="eyebrow">PLANO INTEGRADO</p><h2>Pilares estratégicos</h2><div class="grid cards"><?php foreach($estrategias as $x): ?><article><span class="icon">◌</span><h3><?=e($x['titulo'])?></h3><p><?=e($x['descricao'])?></p></article><?php endforeach ?></div><div class="flow compact"><span>Pesquisa</span><span>Segmentação</span><span>Marketing</span><span>Leads</span><span>Qualificação</span><span>Funil</span><span>Conversão</span><span>Análise</span><span>Otimização</span></div></section>
<section id="funil"><p class="eyebrow">JORNADA COMERCIAL</p><h2>Funil de vendas</h2><div class="funnel"><article><b>Topo do Funil</b><p>Awareness · Alcance<br>Conteúdo · Tráfego</p></article><article><b>Meio do Funil</b><p>Leads · Engajamento<br>Qualificação · Nutrição</p></article><article><b>Fundo do Funil</b><p>Proposta · Negociação<br>Conversão · Venda</p></article><article><b>Pós-venda</b><p>Retenção · Fidelização<br>Upsell · Indicação</p></article></div></section>
<section id="mercados"><p class="eyebrow">ADAPTAÇÃO</p><h2>LATAM × Europa</h2><div class="compare"><article><h3>LATAM</h3><p>Comunicação, idioma, comportamento do consumidor e abordagem comercial devem ser considerados conforme cada mercado e contexto cultural.</p></article><article><h3>Europa</h3><p>A estratégia prevê adaptação cultural e comercial por país, respeitando idioma, práticas de mercado e expectativas de relacionamento.</p></article></div><p class="notice">Este projeto é conceitual; não apresenta estatísticas ou resultados reais.</p></section>
<section id="dados"><p class="eyebrow">CICLO CONTÍNUO</p><h2>Marketing + Vendas + Dados</h2><div class="cycle">Marketing gera demanda <b>→</b> Vendas convertem oportunidades <b>→</b> Dados medem e orientam decisões <b>→</b> Otimização <b>→</b> Marketing</div></section>
<section id="kpis"><p class="eyebrow">ACOMPANHAMENTO</p><h2>Dashboard de KPIs</h2><p class="notice">Indicadores demonstrativos: dados simulados para fins acadêmicos e estratégicos.</p><div class="grid metrics"><?php foreach($kpis as $x): ?><article><b><?=e($x['nome'])?></b><strong><?=e($x['valor']).e($x['unidade'])?></strong><small><?=e($x['descricao'])?></small></article><?php endforeach ?></div><div class="chart"><canvas id="kpiChart"></canvas></div></section>
<section id="premissas" class="split"><div><p class="eyebrow">PREMISSAS</p><h2>Base do planejamento</h2><p>Equipe de três integrantes, pesquisas, hipóteses, ferramentas digitais e adaptação cultural entre LATAM e Europa.</p></div><div><p class="eyebrow">RESTRIÇÕES</p><h2>Escopo consciente</h2><p>Projeto conceitual, equipe reduzida, prazo limitado, ausência de investimento financeiro real e uso de dados simulados.</p></div></section>
<section id="equipe"><p class="eyebrow">PESSOAS</p><h2>Equipe do projeto</h2><div class="grid team"><?php foreach($team as $x): ?><article><div class="avatar"><?=e(mb_substr($x['nome'],0,1))?></div><h3><?=e($x['nome'])?></h3><b><?=e($x['funcao'])?></b><p><?=e($x['responsabilidade'])?></p></article><?php endforeach ?></div></section>
<section id="cronograma"><p class="eyebrow">MARCO TEMPORAL</p><h2>Cronograma</h2><div class="timeline"><?php foreach($timeline as $x): ?><article><b><?=date('d/m/Y',strtotime($x['data']))?></b><h3><?=e($x['titulo'])?></h3><p><?=e($x['descricao'])?></p></article><?php endforeach ?></div></section>
<section id="contato"><p class="eyebrow">CONTATO</p><h2>Vamos conversar</h2><form class="contact" method="post" action="contato.php"><input name="nome" required maxlength="100" placeholder="Nome"><input type="email" name="email" required maxlength="150" placeholder="E-mail"><input name="assunto" required maxlength="150" placeholder="Assunto"><textarea name="mensagem" required maxlength="3000" placeholder="Mensagem"></textarea><button class="button">Enviar mensagem</button></form></section>
<?php require 'includes/footer.php'; ?>
