CREATE DATABASE IF NOT EXISTS scaleup_latam_europe CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE scaleup_latam_europe;
CREATE TABLE usuarios(id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(120) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,senha VARCHAR(255) NOT NULL,nivel VARCHAR(30) NOT NULL DEFAULT 'admin',criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE projeto(id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(150) NOT NULL,id_desafio VARCHAR(30),id_projeto VARCHAR(30),objetivo TEXT,justificativa TEXT,data_inicio DATE,data_fim DATE,atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE equipe(id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(120) NOT NULL,funcao VARCHAR(120) NOT NULL,responsabilidade TEXT,foto VARCHAR(255),email VARCHAR(150));
CREATE TABLE estrategias(id INT AUTO_INCREMENT PRIMARY KEY,titulo VARCHAR(150) NOT NULL,descricao TEXT,categoria VARCHAR(100),ordem INT DEFAULT 0,ativo TINYINT(1) DEFAULT 1);
CREATE TABLE kpis(id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(120) NOT NULL,valor VARCHAR(50),unidade VARCHAR(30),descricao TEXT,atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE timeline(id INT AUTO_INCREMENT PRIMARY KEY,data DATE NOT NULL,titulo VARCHAR(150) NOT NULL,descricao TEXT,ordem INT DEFAULT 0);
CREATE TABLE conteudos(id INT AUTO_INCREMENT PRIMARY KEY,titulo VARCHAR(180) NOT NULL,conteudo TEXT,secao VARCHAR(100),atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE contatos(id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL,assunto VARCHAR(150) NOT NULL,mensagem TEXT NOT NULL,status ENUM('nova','lida') DEFAULT 'nova',criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
-- Após importar, abra install.php uma única vez para criar o usuário inicial com password_hash().
INSERT INTO projeto(nome,id_desafio,id_projeto,objetivo,justificativa,data_inicio,data_fim) VALUES ('ScaleUp LATAM & Europe','163241','22782','Desenvolver uma estratégia completa de marketing e vendas digitais para apoiar a expansão de um produto ou serviço na América Latina e Europa.','Necessidade de estratégia estruturada, adaptação cultural, mensuração de campanhas e integração entre marketing e vendas.','2026-08-03','2026-09-19');
INSERT INTO equipe(nome,funcao,responsabilidade) VALUES ('Mauro Roberto Claro','Gerente / Mentor','Gerência e mentoria do projeto.'),('Gabryel Rodrigues','Desenvolvedor','Desenvolvimento do projeto.'),('Guilherme dos Santos','Desenvolvedor','Desenvolvimento do projeto.'),('Adriano Godoy','Desenvolvedor','Desenvolvimento do projeto.');
INSERT INTO estrategias(titulo,descricao,categoria,ordem) VALUES ('Marketing Digital','Presença e comunicação digital adaptada aos mercados.','Marketing',1),('Geração de Leads','Aquisição de contatos qualificados para o funil.','Aquisição',2),('Funil de Vendas','Estruturação da jornada de oportunidade à venda.','Vendas',3),('Conversão','Aprimoramento de oportunidades comerciais.','Vendas',4),('Análise de Dados','Medição para orientar decisões.','Dados',5),('ROI','Acompanhamento conceitual de retorno.','Dados',6),('Estratégia Cultural','Adaptação de comunicação e abordagem comercial.','Mercados',7),('Integração Marketing + Vendas','Alinhamento contínuo entre geração e conversão.','Integração',8);
INSERT INTO kpis(nome,valor,unidade,descricao) VALUES ('Leads Gerados','82','','Simulado'),('Taxa de Conversão','18','%','Simulado'),('CPL','24','R$','Simulado'),('CAC','61','R$','Simulado'),('ROI','35','%','Simulado'),('Ticket Médio','150','R$','Simulado'),('Taxa de Retenção','72','%','Simulado'),('Oportunidades','26','','Simulado'),('Vendas','12','','Simulado');
INSERT INTO timeline(data,titulo,descricao,ordem) VALUES ('2026-08-03','Início do Projeto','Início do projeto.',1),('2026-09-18','Criação da TAP','Criação da TAP.',2),('2026-09-19','Conclusão','Conclusão do projeto.',3);
