<?php
/**
 * Conteúdo da landing page adaptado por mercado (região + idioma).
 * Cada variante tem linguagem, prova social, canais e CTAs próprios.
 */
const MARKETS = [
    'br' => [
        'region' => 'LATAM', 'lang' => 'pt-BR', 'label' => 'Brasil', 'flag' => '🇧🇷',
        'countries' => ['Brasil'],
        'nav' => ['Problemas', 'Método', 'Funil', 'Mercados', 'KPIs', 'Contato'],
        'hero_tag' => 'Expansão internacional com foco em ROI',
        'hero_title' => 'Escale suas vendas digitais na América Latina e na Europa',
        'hero_text' => 'Estratégia completa de marketing e vendas para startups e scale-ups: mais leads qualificados, mais conversão e retorno medido em cada real investido.',
        'cta_primary' => 'Quero meu diagnóstico gratuito',
        'cta_secondary' => 'Falar no WhatsApp',
        'trust' => ['Diagnóstico em 48h', 'Sem custo inicial', 'Atendimento em português'],
        'problems_title' => 'O que trava a sua expansão hoje?',
        'problems' => [
            ['🧭', 'Sem estratégia clara', 'Entrar em novos países sem plano gera gasto alto e resultado imprevisível.'],
            ['📉', 'Baixa conversão', 'Muitos leads, poucas vendas: o funil vaza entre marketing e comercial.'],
            ['🌎', 'Comunicação genérica', 'A mesma mensagem para todos os países ignora diferenças culturais.'],
            ['📊', 'ROI invisível', 'Sem KPIs definidos, ninguém sabe qual canal realmente dá retorno.'],
            ['🤝', 'Marketing x Vendas', 'Times desalinhados, metas diferentes e oportunidades perdidas.'],
        ],
        'method_title' => 'Método ScaleUp em 4 etapas',
        'method' => [
            ['01', 'Diagnóstico', 'Análise do produto, público e concorrência em cada mercado.'],
            ['02', 'Estratégia regional', 'Posicionamento, mensagens e canais adaptados à cultura local.'],
            ['03', 'Campanhas enxutas', 'Testes de baixo custo em Google, Meta, LinkedIn e canais orgânicos.'],
            ['04', 'Medição e escala', 'KPIs, dashboards e otimização contínua do que gera ROI.'],
        ],
        'funnel_title' => 'Funil de marketing e vendas',
        'funnel' => [
            ['Atração', 'SEO, conteúdo, redes sociais e anúncios de baixo custo', 'Visitantes'],
            ['Captura', 'Landing pages com CTAs claros e iscas digitais', 'Leads'],
            ['Nutrição', 'E-mail, WhatsApp e remarketing segmentados por região', 'MQL'],
            ['Conversão', 'Abordagem comercial consultiva e demonstrações', 'SQL'],
            ['Fidelização', 'Onboarding, upsell e indicação', 'Clientes'],
        ],
        'markets_title' => 'Uma estratégia, dois continentes',
        'latam' => ['América Latina', 'Relacionamento próximo, WhatsApp e redes sociais como canais principais, prova social local e condições de pagamento flexíveis (Pix, parcelamento).'],
        'europe' => ['Europa', 'Comunicação objetiva, foco em qualidade, sustentabilidade e conformidade com a GDPR. LinkedIn e e-mail fortes no B2B, idioma local em cada país.'],
        'kpi_title' => 'KPIs que vamos acompanhar',
        'kpis' => ['CPL – Custo por lead', 'Taxa de conversão do funil', 'CAC – Custo de aquisição', 'ROI e ROAS por canal', 'LTV / CAC', 'Ciclo de vendas'],
        'form_title' => 'Receba um diagnóstico gratuito da sua expansão',
        'form_text' => 'Preencha em menos de 1 minuto. Um especialista retorna em até 48h.',
        'f_name' => 'Nome completo', 'f_email' => 'E-mail corporativo', 'f_phone' => 'WhatsApp', 'f_company' => 'Empresa',
        'f_role' => 'Cargo', 'f_country' => 'País', 'f_interest' => 'Mercado de interesse', 'f_message' => 'Qual é o seu principal desafio?',
        'f_consent' => 'Aceito receber contato e concordo com o tratamento dos meus dados conforme a LGPD.',
        'f_submit' => 'Quero meu diagnóstico',
        'f_success' => 'Recebemos seus dados! Em breve entraremos em contato.',
        'f_error' => 'Verifique os campos obrigatórios e tente novamente.',
        'interests' => ['LATAM', 'Europa', 'LATAM + Europa'],
        'faq_title' => 'Perguntas frequentes',
        'faq' => [
            ['Preciso ter um grande orçamento?', 'Não. Priorizamos canais orgânicos e testes de baixo custo, escalando apenas o que comprovar retorno.'],
            ['Quanto tempo leva para ver resultados?', 'Os primeiros testes de campanha geram dados em 2 a 4 semanas.'],
            ['Funciona para B2B e B2C?', 'Sim. Para B2B usamos LinkedIn e e-mail; para B2C, Meta Ads, Google e influenciadores locais.'],
        ],
        'footer' => 'Projeto acadêmico – estratégia baseada em hipóteses e dados simulados.',
    ],
    'es' => [
        'region' => 'LATAM', 'lang' => 'es', 'label' => 'LATAM (ES)', 'flag' => '🇲🇽',
        'countries' => ['México', 'Argentina', 'Chile', 'Colombia', 'Perú', 'Uruguay', 'Otro'],
        'nav' => ['Problemas', 'Método', 'Embudo', 'Mercados', 'KPIs', 'Contacto'],
        'hero_tag' => 'Expansión internacional con foco en ROI',
        'hero_title' => 'Escala tus ventas digitales en Latinoamérica y Europa',
        'hero_text' => 'Estrategia completa de marketing y ventas para startups y scale-ups: más leads calificados, más conversión y retorno medido en cada peso invertido.',
        'cta_primary' => 'Quiero mi diagnóstico gratis',
        'cta_secondary' => 'Escríbenos por WhatsApp',
        'trust' => ['Diagnóstico en 48h', 'Sin costo inicial', 'Atención en español'],
        'problems_title' => '¿Qué frena tu expansión hoy?',
        'problems' => [
            ['🧭', 'Sin estrategia clara', 'Entrar a nuevos países sin un plan genera gastos altos y resultados inciertos.'],
            ['📉', 'Baja conversión', 'Muchos leads, pocas ventas: el embudo se pierde entre marketing y ventas.'],
            ['🌎', 'Comunicación genérica', 'El mismo mensaje para todos los países ignora las diferencias culturales.'],
            ['📊', 'ROI invisible', 'Sin KPIs definidos nadie sabe qué canal realmente genera retorno.'],
            ['🤝', 'Marketing vs. Ventas', 'Equipos desalineados, metas distintas y oportunidades perdidas.'],
        ],
        'method_title' => 'Método ScaleUp en 4 etapas',
        'method' => [
            ['01', 'Diagnóstico', 'Análisis del producto, público y competencia en cada mercado.'],
            ['02', 'Estrategia regional', 'Posicionamiento, mensajes y canales adaptados a la cultura local.'],
            ['03', 'Campañas ágiles', 'Pruebas de bajo costo en Google, Meta, LinkedIn y canales orgánicos.'],
            ['04', 'Medición y escala', 'KPIs, dashboards y optimización continua de lo que genera ROI.'],
        ],
        'funnel_title' => 'Embudo de marketing y ventas',
        'funnel' => [
            ['Atracción', 'SEO, contenido, redes sociales y anuncios de bajo costo', 'Visitantes'],
            ['Captura', 'Landing pages con CTAs claros y lead magnets', 'Leads'],
            ['Nutrición', 'E-mail, WhatsApp y remarketing segmentados por región', 'MQL'],
            ['Conversión', 'Venta consultiva y demostraciones', 'SQL'],
            ['Fidelización', 'Onboarding, upsell y referidos', 'Clientes'],
        ],
        'markets_title' => 'Una estrategia, dos continentes',
        'latam' => ['Latinoamérica', 'Relación cercana, WhatsApp y redes sociales como canales clave, prueba social local y opciones de pago flexibles (cuotas, pagos locales).'],
        'europe' => ['Europa', 'Comunicación directa, foco en calidad, sostenibilidad y cumplimiento del RGPD. LinkedIn y e-mail fuertes en B2B, idioma local en cada país.'],
        'kpi_title' => 'KPIs que vamos a medir',
        'kpis' => ['CPL – Costo por lead', 'Tasa de conversión del embudo', 'CAC – Costo de adquisición', 'ROI y ROAS por canal', 'LTV / CAC', 'Ciclo de ventas'],
        'form_title' => 'Recibe un diagnóstico gratuito de tu expansión',
        'form_text' => 'Complétalo en menos de 1 minuto. Un especialista te contacta en 48h.',
        'f_name' => 'Nombre completo', 'f_email' => 'E-mail corporativo', 'f_phone' => 'WhatsApp', 'f_company' => 'Empresa',
        'f_role' => 'Cargo', 'f_country' => 'País', 'f_interest' => 'Mercado de interés', 'f_message' => '¿Cuál es tu principal desafío?',
        'f_consent' => 'Acepto ser contactado y el tratamiento de mis datos personales.',
        'f_submit' => 'Quiero mi diagnóstico',
        'f_success' => '¡Recibimos tus datos! Pronto nos pondremos en contacto.',
        'f_error' => 'Revisa los campos obligatorios e inténtalo de nuevo.',
        'interests' => ['LATAM', 'Europa', 'LATAM + Europa'],
        'faq_title' => 'Preguntas frecuentes',
        'faq' => [
            ['¿Necesito un gran presupuesto?', 'No. Priorizamos canales orgánicos y pruebas de bajo costo, escalando solo lo que demuestra retorno.'],
            ['¿Cuándo veré resultados?', 'Las primeras pruebas de campaña generan datos en 2 a 4 semanas.'],
            ['¿Funciona para B2B y B2C?', 'Sí. En B2B usamos LinkedIn y e-mail; en B2C, Meta Ads, Google e influencers locales.'],
        ],
        'footer' => 'Proyecto académico – estrategia basada en hipótesis y datos simulados.',
    ],
    'eu' => [
        'region' => 'EUROPE', 'lang' => 'en', 'label' => 'Europe (EN)', 'flag' => '🇪🇺',
        'countries' => ['Portugal', 'Spain', 'France', 'Germany', 'Italy', 'Netherlands', 'United Kingdom', 'Other'],
        'nav' => ['Challenges', 'Method', 'Funnel', 'Markets', 'KPIs', 'Contact'],
        'hero_tag' => 'International growth, measured by ROI',
        'hero_title' => 'Scale your digital sales across Europe and Latin America',
        'hero_text' => 'A complete marketing and sales strategy for startups and scale-ups: qualified leads, higher conversion and transparent return on every euro invested.',
        'cta_primary' => 'Book a free assessment',
        'cta_secondary' => 'Contact us by e-mail',
        'trust' => ['GDPR compliant', 'Assessment within 48h', 'No upfront cost'],
        'problems_title' => 'What is holding back your expansion?',
        'problems' => [
            ['🧭', 'No clear strategy', 'Entering new countries without a plan means high costs and unpredictable results.'],
            ['📉', 'Low conversion', 'Plenty of leads, few deals: the funnel leaks between marketing and sales.'],
            ['🌎', 'Generic messaging', 'One message for every country ignores cultural differences.'],
            ['📊', 'Invisible ROI', 'Without defined KPIs, no one knows which channel truly pays off.'],
            ['🤝', 'Marketing vs. Sales', 'Misaligned teams, different goals and missed opportunities.'],
        ],
        'method_title' => 'The ScaleUp method in 4 steps',
        'method' => [
            ['01', 'Assessment', 'Product, audience and competitor analysis for each market.'],
            ['02', 'Regional strategy', 'Positioning, messaging and channels adapted to local culture.'],
            ['03', 'Lean campaigns', 'Low-cost tests on Google, Meta, LinkedIn and organic channels.'],
            ['04', 'Measure & scale', 'KPIs, dashboards and continuous optimisation of what drives ROI.'],
        ],
        'funnel_title' => 'Marketing & sales funnel',
        'funnel' => [
            ['Attract', 'SEO, content, social media and low-cost ads', 'Visitors'],
            ['Capture', 'Landing pages with clear CTAs and lead magnets', 'Leads'],
            ['Nurture', 'E-mail sequences, LinkedIn and region-based retargeting', 'MQL'],
            ['Convert', 'Consultative sales and product demos', 'SQL'],
            ['Retain', 'Onboarding, upsell and referrals', 'Customers'],
        ],
        'markets_title' => 'One strategy, two continents',
        'latam' => ['Latin America', 'Close relationships, WhatsApp and social media as key channels, local social proof and flexible payment options.'],
        'europe' => ['Europe', 'Direct communication, focus on quality, sustainability and GDPR compliance. LinkedIn and e-mail drive B2B, local language in every country.'],
        'kpi_title' => 'KPIs we track',
        'kpis' => ['CPL – Cost per lead', 'Funnel conversion rate', 'CAC – Customer acquisition cost', 'ROI & ROAS per channel', 'LTV / CAC', 'Sales cycle length'],
        'form_title' => 'Get a free assessment of your expansion',
        'form_text' => 'Takes less than a minute. A specialist will reply within 48 hours.',
        'f_name' => 'Full name', 'f_email' => 'Business e-mail', 'f_phone' => 'Phone', 'f_company' => 'Company',
        'f_role' => 'Job title', 'f_country' => 'Country', 'f_interest' => 'Target market', 'f_message' => 'What is your main challenge?',
        'f_consent' => 'I agree to be contacted and to the processing of my personal data in accordance with the GDPR.',
        'f_submit' => 'Request assessment',
        'f_success' => 'Thank you! We will get in touch shortly.',
        'f_error' => 'Please check the required fields and try again.',
        'interests' => ['Europe', 'LATAM', 'Europe + LATAM'],
        'faq_title' => 'FAQ',
        'faq' => [
            ['Do I need a large budget?', 'No. We prioritise organic channels and low-cost tests, scaling only what proves its return.'],
            ['How soon will I see results?', 'First campaign tests produce data within 2 to 4 weeks.'],
            ['Does it work for B2B and B2C?', 'Yes. B2B relies on LinkedIn and e-mail; B2C on Meta Ads, Google and local creators.'],
        ],
        'footer' => 'Academic project – strategy based on hypotheses and simulated data.',
    ],
];

function current_market(): string
{
    $m = $_GET['m'] ?? $_SESSION['market'] ?? null;
    if (!$m || !isset(MARKETS[$m])) {
        $accept = strtolower($_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? '');
        $m = str_starts_with($accept, 'es') ? 'es' : (str_starts_with($accept, 'en') ? 'eu' : 'br');
    }
    $_SESSION['market'] = $m;
    return $m;
}
